// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Model.Data.Instance
{
    [DbContext(typeof(SapContext))]
    public partial class SapContextModel : RuntimeModel
    {
        static SapContextModel()
        {
            var model = new SapContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static SapContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
