// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Model.Data.Instance
{
    public partial class SapContextModel
    {
        partial void Initialize()
        {
            var brand = BrandEntityType.Create(this);
            var category = CategoryEntityType.Create(this);
            var conversion = ConversionEntityType.Create(this);
            var inventory = InventoryEntityType.Create(this);
            var log = LogEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var record = RecordEntityType.Create(this);
            var role = RoleEntityType.Create(this);
            var unit = UnitEntityType.Create(this);
            var user = UserEntityType.Create(this);

            ConversionEntityType.CreateForeignKey1(conversion, unit);
            ConversionEntityType.CreateForeignKey2(conversion, unit);
            InventoryEntityType.CreateForeignKey1(inventory, product);
            LogEntityType.CreateForeignKey1(log, user);
            ProductEntityType.CreateForeignKey1(product, brand);
            ProductEntityType.CreateForeignKey2(product, category);
            ProductEntityType.CreateForeignKey3(product, unit);
            RecordEntityType.CreateForeignKey1(record, product);
            RecordEntityType.CreateForeignKey2(record, unit);
            RecordEntityType.CreateForeignKey3(record, user);
            UserEntityType.CreateForeignKey1(user, role);

            BrandEntityType.CreateAnnotations(brand);
            CategoryEntityType.CreateAnnotations(category);
            ConversionEntityType.CreateAnnotations(conversion);
            InventoryEntityType.CreateAnnotations(inventory);
            LogEntityType.CreateAnnotations(log);
            ProductEntityType.CreateAnnotations(product);
            RecordEntityType.CreateAnnotations(record);
            RoleEntityType.CreateAnnotations(role);
            UnitEntityType.CreateAnnotations(unit);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "6.0.35");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
